#ifndef _FUNCONFIG_H
#define _FUNCONFIG_H

#define FUNCONF_USE_DEBUGPRINTF  1
#define CH32V003           1
#define FUNCONF_USE_HSE 0
#define FUNCONF_USE_HSI 1
#define FUNCONF_USE_PLL 1
#define FUNCONF_HSE_BYPASS 0
#define FUNCONF_USE_CLK_SEC 1
#define FUNCONF_USE_UARTPRINTF 0
#define FUNCONF_NULL_PRINTF 0
#define FUNCONF_TINYVECTOR 0
#define FUNCONF_DEBUGPRINTF_TIMEOUT 160000
#define FUNCONF_SYSTICK_USE_HCLK 0

#endif
