[env:tiny816]
platform = atmelmegaavr
board = ATtiny816
framework = arduino

# This tells PIO to use the megaTinyCore logic
board_build.f_cpu = 16000000L

; Tell the core to use the internal oscillator
board_hardware.oscillator = internal

; Optional: If you want to disable the Brown-Out Detector entirely 
; at the hardware level to help your battery survive the NeoPixels
board_hardware.bod = disabled

# megaTinyCore specific packages
platform_packages =
    framework-arduino-megaavr-megatinycore@https://github.com/SpenceKonde/megaTinyCore.git
# Use PlatformIO's native board_build directive for the millis timer
# This properly unsets TCA0 and configures the RTC without conflict

# Force the inclusion of the Touch library
build_flags = -DTINY_TOUCH
              -D MILLIS_USE_TIMERA0

; Strip out any conflicting timer flags PlatformIO might be secretly injecting

build_unflags = 
    -DMILLIS_USE_TIMERB0
    -DMILLIS_USE_TIMERB1
    -DMILLIS_USE_TIMERB2
    -DMILLIS_USE_TIMERB3
    -DMILLIS_USE_TIMERB4
    -DMILLIS_USE_TIMERB5
    -DMILLIS_USE_TIMERD0
    -DMILLIS_USE_TIMERRTC


# Setup for UPDI programming (using a serial adapter + resistor)
upload_protocol = serialupdi
upload_speed = 230400  
upload_flags =
    -xrtsdtr=high
#    -v               ; Optional: Add for more verbose output if debugging

lib_deps =
    adafruit/Adafruit NeoPixel @ ^1.11.0
    PTC





    