[env:tiny816]
platform = atmelmegaavr
board = at_tiny816
framework = arduino

# Setup for UPDI programming (using a serial adapter + resistor)
upload_protocol = serialupdi
upload_flags =
    -xrtsdtr=high

lib_deps =
    # Standard touch library for megaTinyCore
    https://github.com/SpenceKonde/megaTinyCore